version: "3.8"

services:
  mongodb:
    image: mongo
    container_name: sejong-mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: sejongTicketDB
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
